# Generated by Django 3.0.5 on 2020-04-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_now',
            field=models.BooleanField(default=True),
        ),
    ]
