# Generated by Django 3.0.5 on 2020-04-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_publish_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Tablet_Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_now',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='Buying_Rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Pieces',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Selling_Rate',
            field=models.FloatField(null=True),
        ),
    ]
