# Generated by Django 3.0.5 on 2020-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200415_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Profit',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
